"""empty message

Revision ID: 0140d83b0b36
Revises: b668b194100e
Create Date: 2021-10-23 14:19:56.434617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0140d83b0b36'
down_revision = 'b668b194100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('in_address', sa.String(length=100), nullable=False),
    sa.Column('delivery', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=False),
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_photo', sa.String(length=250), nullable=False),
    sa.Column('item_description', sa.String(length=250), nullable=False),
    sa.Column('item_stock', sa.Integer(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('balance', sa.Column('storename', sa.String(length=30), nullable=False))
    op.add_column('seller', sa.Column('address', sa.String(length=50), nullable=False))
    op.add_column('seller', sa.Column('phonenumber', sa.String(length=15), nullable=False))
    op.add_column('seller', sa.Column('storename', sa.String(length=30), nullable=False))
    op.add_column('seller', sa.Column('category', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'category')
    op.drop_column('seller', 'storename')
    op.drop_column('seller', 'phonenumber')
    op.drop_column('seller', 'address')
    op.drop_column('balance', 'storename')
    op.drop_table('sale')
    op.drop_table('product')
    op.drop_table('payment')
    op.drop_table('favorite')
    op.drop_table('dispatch')
    # ### end Alembic commands ###
