"""empty message

Revision ID: 09a5510d7cfe
Revises: 
Create Date: 2021-10-04 17:40:28.012230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a5510d7cfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postseller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_photo', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.String(length=150), nullable=False),
    sa.Column('item_stock', sa.String(length=15), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('seller')
    op.drop_table('postseller')
    op.drop_table('favorites')
    op.drop_table('buyer')
    # ### end Alembic commands ###
