"""empty message

Revision ID: 09c02923bc8b
Revises: d5bc11944543
Create Date: 2021-10-06 18:48:22.931736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c02923bc8b'
down_revision = 'd5bc11944543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('last_deposit', sa.Integer(), nullable=False),
    sa.Column('last_withdraw', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('in_address', sa.String(length=50), nullable=False),
    sa.Column('delivery', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=False),
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('dispatch')
    op.drop_table('balance')
    # ### end Alembic commands ###
