"""empty message

Revision ID: 276634d110b9
Revises: 8491edb47222
Create Date: 2021-10-05 11:51:24.242192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276634d110b9'
down_revision = '8491edb47222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sellerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], name='sales_buyerID_fkey'),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], name='sales_sellerID_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_pkey')
    )
    op.drop_table('sale')
    # ### end Alembic commands ###
