"""empty message

Revision ID: 27f5c54aa917
Revises: f0f157b8969c
Create Date: 2021-10-30 13:30:34.003649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f5c54aa917'
down_revision = 'f0f157b8969c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
