"""empty message

Revision ID: 292c93f818a9
Revises: 09a5510d7cfe
Create Date: 2021-10-04 21:28:38.676128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292c93f818a9'
down_revision = '09a5510d7cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_photo', sa.String(length=250), nullable=False),
    sa.Column('item_description', sa.String(length=150), nullable=False),
    sa.Column('item_stock', sa.String(length=15), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    op.drop_table('postseller')
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sellerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], name='sales_buyerID_fkey'),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], name='sales_sellerID_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_pkey')
    )
    op.create_table('postseller',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('item_title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_photo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('item_stock', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('item_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='postseller_pkey')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('sale')
    op.drop_table('product')
    op.drop_table('favorite')
    # ### end Alembic commands ###
