"""empty message

Revision ID: 324b7c23be43
Revises: c37d93733fc3
Create Date: 2021-10-20 20:11:04.615994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324b7c23be43'
down_revision = 'c37d93733fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hola', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hola')
    # ### end Alembic commands ###
