"""empty message

Revision ID: 387b72c4ec90
Revises: 863f3a433aee
Create Date: 2021-10-20 20:01:54.804771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b72c4ec90'
down_revision = '863f3a433aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('hola', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyer', 'hola')
    # ### end Alembic commands ###
