"""empty message

Revision ID: 60ca1ecbf8ef
Revises: 168b0b217387
Create Date: 2021-11-13 00:49:51.686892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ca1ecbf8ef'
down_revision = '168b0b217387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'storename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('storename', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
