"""empty message

Revision ID: 6ba7e0f991cc
Revises: 
Create Date: 2021-10-27 22:02:20.837139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba7e0f991cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('file', sa.String(length=250), nullable=True))
    op.drop_column('product', 'item_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('item_photo', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('product', 'file')
    # ### end Alembic commands ###
