"""empty message

Revision ID: 6fd72b1f0a37
Revises: 7af8ad3fcc9e
Create Date: 2021-10-21 20:16:35.725105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd72b1f0a37'
down_revision = '7af8ad3fcc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('rut', sa.String(length=12), nullable=False))
    op.drop_column('buyer', 'hola')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('hola', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('buyer', 'rut')
    # ### end Alembic commands ###
