"""empty message

Revision ID: 7af8ad3fcc9e
Revises: 156516c2a095
Create Date: 2021-10-21 20:15:17.439831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af8ad3fcc9e'
down_revision = '156516c2a095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('hola', sa.String(length=30), nullable=False))
    op.drop_column('buyer', 'rut')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('rut', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('buyer', 'hola')
    # ### end Alembic commands ###
