"""empty message

Revision ID: 7f2986704bcf
Revises: 9a6cb23306b8
Create Date: 2021-10-20 20:25:31.390995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2986704bcf'
down_revision = '9a6cb23306b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'probando')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('probando', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
