"""empty message

Revision ID: 8491edb47222
Revises: 3318536500c0
Create Date: 2021-10-04 13:54:31.743183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8491edb47222'
down_revision = '3318536500c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sellerID', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('buyerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'seller', ['sellerID'], ['id'])
    op.create_foreign_key(None, 'sales', 'buyer', ['buyerID'], ['id'])
    op.drop_column('sales', 'buyer')
    op.drop_column('sales', 'seller')
    op.drop_column('sales', 'amount')
    op.add_column('seller', sa.Column('store_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'store_name')
    op.add_column('sales', sa.Column('amount', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('seller', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('buyer', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'buyerID')
    op.drop_column('sales', 'sellerID')
    # ### end Alembic commands ###
