"""empty message

Revision ID: 863f3a433aee
Revises: 276634d110b9
Create Date: 2021-10-05 12:31:14.358862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863f3a433aee'
down_revision = '276634d110b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=30), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_photo', sa.String(length=250), nullable=False),
    sa.Column('item_description', sa.String(length=250), nullable=False),
    sa.Column('item_stock', sa.String(length=15), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sale', sa.Column('productID', sa.Integer(), nullable=True))
    op.add_column('sale', sa.Column('item_title', sa.Integer(), nullable=False))
    op.add_column('sale', sa.Column('item_price', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sale', 'product', ['productID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'item_price')
    op.drop_column('sale', 'item_title')
    op.drop_column('sale', 'productID')
    op.drop_table('product')
    # ### end Alembic commands ###
