"""empty message

Revision ID: 89b255aca090
Revises: 09c02923bc8b
Create Date: 2021-10-14 23:54:36.330460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b255aca090'
down_revision = '09c02923bc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sa.String(length=50), nullable=False))
    op.add_column('seller', sa.Column('phonenumber', sa.String(length=15), nullable=False))
    op.add_column('seller', sa.Column('category', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'category')
    op.drop_column('seller', 'phonenumber')
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
