"""empty message

Revision ID: 92f6232f4463
Revises: 
Create Date: 2021-11-04 23:28:41.078353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f6232f4463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('file', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
