"""empty message

Revision ID: 9a6cb23306b8
Revises: e1c3437d57d0
Create Date: 2021-10-20 20:23:20.807571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6cb23306b8'
down_revision = 'e1c3437d57d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('rut', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'rut')
    # ### end Alembic commands ###
