"""empty message

Revision ID: b29e7cfc7039
Revises: 387b72c4ec90
Create Date: 2021-10-20 20:07:58.910604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29e7cfc7039'
down_revision = '387b72c4ec90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyer', 'hola')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('hola', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
