"""empty message

Revision ID: b668b194100e
Revises: fbd23ca85b47
Create Date: 2021-10-06 18:05:14.694550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b668b194100e'
down_revision = 'fbd23ca85b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('sellerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'balance', 'seller', ['sellerID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.drop_column('balance', 'sellerID')
    # ### end Alembic commands ###
