"""empty message

Revision ID: c37d93733fc3
Revises: 23b10af22fd4
Create Date: 2021-10-16 12:37:01.921846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37d93733fc3'
down_revision = '23b10af22fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('storename', sa.String(length=30), nullable=False))
    op.drop_column('balance', 'store_name')
    op.add_column('favorite', sa.Column('storename', sa.String(length=30), nullable=False))
    op.drop_column('favorite', 'store_name')
    op.add_column('product', sa.Column('storename', sa.String(length=30), nullable=False))
    op.drop_column('product', 'store_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('store_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('product', 'storename')
    op.add_column('favorite', sa.Column('store_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('favorite', 'storename')
    op.add_column('balance', sa.Column('store_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('balance', 'storename')
    # ### end Alembic commands ###
