"""empty message

Revision ID: c4e9dfdc33d0
Revises: 27f5c54aa917
Create Date: 2021-10-30 13:31:30.319371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e9dfdc33d0'
down_revision = '27f5c54aa917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('firstname', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'firstname')
    # ### end Alembic commands ###
