"""empty message

Revision ID: d5bc11944543
Revises: 292c93f818a9
Create Date: 2021-10-05 23:10:44.312454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bc11944543'
down_revision = '292c93f818a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('buyerID', sa.Integer(), nullable=True))
    op.add_column('favorite', sa.Column('sellerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'seller', ['sellerID'], ['id'])
    op.create_foreign_key(None, 'favorite', 'buyer', ['buyerID'], ['id'])
    op.add_column('product', sa.Column('sellerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'seller', ['sellerID'], ['id'])
    op.add_column('sale', sa.Column('productID', sa.Integer(), nullable=True))
    op.add_column('sale', sa.Column('item_title', sa.Integer(), nullable=False))
    op.add_column('sale', sa.Column('item_price', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sale', 'product', ['productID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'item_price')
    op.drop_column('sale', 'item_title')
    op.drop_column('sale', 'productID')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'sellerID')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'sellerID')
    op.drop_column('favorite', 'buyerID')
    # ### end Alembic commands ###
