"""empty message

Revision ID: e1c3437d57d0
Revises: f010c83fa61d
Create Date: 2021-10-20 20:20:59.914976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c3437d57d0'
down_revision = 'f010c83fa61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'rut')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('rut', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
