"""empty message

Revision ID: e1fca6e67a6a
Revises: 
Create Date: 2021-10-03 22:00:16.931794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fca6e67a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=True),
    sa.Column('last_deposit', sa.Integer(), nullable=True),
    sa.Column('last_withdraw', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_1', sa.String(length=10), nullable=True),
    sa.Column('category_2', sa.String(length=10), nullable=True),
    sa.Column('category_3', sa.String(length=10), nullable=True),
    sa.Column('category_4', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=50), nullable=True),
    sa.Column('delivery_option', sa.String(length=10), nullable=True),
    sa.Column('payment_option', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    op.drop_table('filter_')
    op.drop_table('category')
    op.drop_table('buyer')
    op.drop_table('balance')
    # ### end Alembic commands ###
