"""empty message

Revision ID: e9ecb6d1bc38
Revises: 
Create Date: 2021-11-09 16:32:00.225374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ecb6d1bc38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.String(length=250), nullable=False),
    sa.Column('item_stock', sa.Integer(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'images', 'product', ['productid'], ['id'])
    op.create_foreign_key(None, 'sale', 'product', ['productID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_table('product')
    # ### end Alembic commands ###
