"""empty message

Revision ID: f010c83fa61d
Revises: 324b7c23be43
Create Date: 2021-10-20 20:14:22.058274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f010c83fa61d'
down_revision = '324b7c23be43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('probando', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'probando')
    # ### end Alembic commands ###
