"""empty message

Revision ID: f0f157b8969c
Revises: 
Create Date: 2021-10-30 12:58:36.544770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f157b8969c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=False),
    sa.Column('credit', sa.Boolean(), nullable=False),
    sa.Column('transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=False),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('last_deposit', sa.Integer(), nullable=False),
    sa.Column('last_withdraw', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('in_address', sa.String(length=100), nullable=False),
    sa.Column('delivery', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('storename', sa.String(length=30), nullable=False),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_photo', sa.String(length=250), nullable=False),
    sa.Column('item_description', sa.String(length=250), nullable=False),
    sa.Column('item_stock', sa.Integer(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerID', sa.Integer(), nullable=True),
    sa.Column('buyerID', sa.Integer(), nullable=True),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('item_title', sa.String(length=50), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyerID'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sellerID'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('product')
    op.drop_table('favorite')
    op.drop_table('dispatch')
    op.drop_table('balance')
    op.drop_table('seller')
    op.drop_table('payment')
    op.drop_table('category')
    op.drop_table('buyer')
    # ### end Alembic commands ###
