"""empty message

Revision ID: fbd23ca85b47
Revises: e1fca6e67a6a
Create Date: 2021-10-05 00:24:50.010156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd23ca85b47'
down_revision = 'e1fca6e67a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('category_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('category_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('category_4', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.create_table('filter_',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delivery_option', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('payment_option', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='filter__pkey')
    )
    # ### end Alembic commands ###
